
[[params.profileMode.buttons]]
name = "Archives"
url = "/archives/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Recent"
url = "/recent/"


[[menu.main]]
identifier = "link"
name = "Download"
url = "https://hugonest.github.io/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
name = "Search"
url = "/search/"
weight = 50
